coverage:
  status:
    project:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags: karma
    patch:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags: karma
flags:
  unittests:
    paths:
      - bundles/cif-connector-graphql/
      - bundles/cif-virtual-catalog/
  karma:
    paths:
      - content/cif-connector/